---
version: '2.4'

services:
  manage-orgs:
    image: "hmctspublic.azurecr.io/xui/mo-webapp@sha256:66b609d8bcc6ad38e090b60b3cae65d6a68a5c9dccabce89921f527b7137f418"
    environment:
      MICROSERVICE: xui_webapp
      PROTOCOL: http
      PUI_ENV: local

      S2S_SERVICE: http://service-auth-provider-api:8080
      IDAM_WEB_SERVICE: http://localhost:3501
      IDAM_API_SERVICE: http://idam-api:5000
      IDAM_CLIENT: xui_webapp_mo
      OAUTH_CALLBACK_URL: /oauth2/callback
      RD_PROFESSIONAL_API_SERVICE: http://wiremock:8080
      MANAGE_CASE_LINK: http://localhost:3333/cases
      MANAGE_ORG_LINK: http://localhost:3000
      SERVICES_CCD_DATA_STORE_API: http://ccd-data-store-api:4452
      SERVICES_MCA_PROXY_API: http://case-assignment:4454

      REDISCLOUD_URL: http://dummyrediscloudurl

      # local launch darkly client required to enable unassigned-cases feature
      LAUNCH_DARKLY_CLIENT_ID: 5f902f8167730c09cbfc5349

      FEATURE_REDIS_ENABLED: "false"
      FEATURE_APP_INSIGHTS_ENABLED: "false"
      FEATURE_SECURE_COOKIE_ENABLED: "false"
      APPINSIGHTS_INSTRUMENTATIONKEY: fake
      GOOGLE_ANALYTICS_KEY: fake

      S2S_SECRET:  "${IDAM_KEY_XUI_WEBAPP}"
      IDAM_SECRET: "${OAUTH2_CLIENT_XUI_MO}"

    ports:
      - 3000:3000
    depends_on:
      idam-api:
        condition: service_started
      ccd-data-store-api:
        condition: service_started
    networks:
      - ccd-network

  xui:
    image: "hmctspublic.azurecr.io/xui/webapp:pr-616-e49ee382"
    environment:
      MICROSERVICE: xui_webapp
      PROTOCOL: http
      XUI_ENV: local

      SERVICES_CCD_COMPONENT_API: http://ccd-api-gateway:3453
      SERVICES_CCD_DATA_STORE_API: http://ccd-data-store-api:4452
      SERVICES_DOCUMENTS_API: http://dm-store:8080
      SERVICES_S2S: http://service-auth-provider-api:8080
      SERVICES_IDAM_LOGIN_URL: http://localhost:3501
      SERVICES_IDAM_API_URL: http://idam-api:5000
      SERVICES_IDAM_OAUTH_CALLBACK_URL: /oauth2/callback
      SERVICES_IDAM_CLIENT_ID: xui_webapp
      SERVICES_PAYMENTS_URL: http://wiremock:8080
      SERVICES_PRD_API: http://wiremock:8080

      SERVICES_EM_ANNO_API: http://ccd-api-gateway:3453
      REDISCLOUD_URL: http://dummyrediscloudurl

      #LAUNCH_DARKLY_CLIENT_ID must be set to enable share a case functionality
      LAUNCH_DARKLY_CLIENT_ID: dummy

      FEATURE_REDIS_ENABLED: "false"
      FEATURE_APP_INSIGHTS_ENABLED: "false"
      FEATURE_SECURE_COOKIE_ENABLED: "false"
      APPINSIGHTS_INSTRUMENTATIONKEY: fake

      S2S_SECRET:  "${IDAM_KEY_XUI_WEBAPP}"
      IDAM_SECRET: "${OAUTH2_CLIENT_XUI}"

      JURISDICTIONS: "CIVIL"

    ports:
      - 3333:3000
    depends_on:
      idam-api:
        condition: service_started
      ccd-data-store-api:
        condition: service_started
    networks:
      - ccd-network

networks:
  ccd-network:
    external: true
